# -*- coding: utf-8 -*-
"""Data_Preprop_aug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VIPhM9LwRvEIbIJhANSID9JthwjvDR2
"""

print("Antas")

import pandas as pd
import numpy as np
try:
    import ctgan
    print("CTGAN is installed.")
except ImportError:
    print("CTGAN is not installed.")

try:
    import imblearn
    print("imblearn is installed.")
except ImportError:
    print("imblearn is not installed.")


import pandas as pd
import numpy as np
from ctgan import CTGAN
import warnings
warnings.filterwarnings('ignore')

#LOAD THE DATA
df = pd.read_csv('/content/dataset.csv')
print(df.head())
print("Loading done")

# Clean hidden spaces from column names and text
df.columns = df.columns.str.strip()
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = df[col].astype(str).str.strip()

df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

# Standardize the Target Column
df['Labelling'] = df['Labelling'].map({'Depressed': 1, 'Not': 0, 'nan': np.nan})
df = df.dropna(subset=['Labelling'])
df['Labelling'] = df['Labelling'].astype(int)

# Fix known typos
if 'Current Appereance Acceptance' in df.columns:
    df['Current Appereance Acceptance'] = df['Current Appereance Acceptance'].replace({'YY': 'Yes'})

#GAN IMplemwntation

# CTGAN needs to know which columns are categories (text/discrete) vs continuous numbers (like Age)
discrete_columns = [
    'Gravida', 'Female Education', 'Husband Education', 'Working Status',
    'Physical Health', 'Previous Miscarriage', 'Sufficient Money for Basic Needs',
    'Current Appereance Acceptance', 'Family System', 'Male Gender Preference',
    'Relationship with Mother in-law', 'Labelling'
]

# 3. TRAIN THE GAN (PHASE 2)
print("Initializing CTGAN...")
#epoch =300
ctgan_model = CTGAN(epochs=300, verbose=True)

print("Training the GAN on 14,000 real patients... (This might take a few minutes)")
ctgan_model.fit(df, discrete_columns)

rows_needed = 16000
print(f"Training complete! Generating {rows_needed} synthetic patients...")
synthetic_data = ctgan_model.sample(rows_needed)

# 5. MERGE AND SAVE
final_30k_df = pd.concat([df, synthetic_data], ignore_index=True)

print(final_30k_df.shape)

# Save to CSV
output_filename = '30k_ppd_CTGAN.csv'
final_30k_df.to_csv(output_filename, index=False)

print(f"Success! Final dataset shape: {final_30k_df.shape}")
print(output_filename)